### PR TITLE
Add new Cmdlets to enable and disable flights

### PR DESCRIPTION
**Pull request by fhoo**
Two new Cmdlets to make the database entries to enable or disable a flight. The FlightingServiceCatalogID is expected to already be setup in the web.config

### CODE REVIEW

**Comment by Splaxi** [comment]
Nice work!

Do you believe that it is doable to fix the web.config requirement in another cmdlet?

Running the sql the sql script from the link, does that make the entry in the web.config file or is it a manual task to add it to the web.config file? 🤔

**Comment by fhoo** [comment]
Adding the entry in the web.config is a "manual" task, but should be possible to do in another or the same cmdlet. The two reasons I didn't do it, are:

1. I'm not sure whether the entry is already there in new environments and only has to be filled with a value

1.

**Comment by Splaxi** [comment]
Could you share a sample web.config file with the entry?

Then I can compare with a freshly deployed machine and see if I can get it to work. 

Do you know of a simple flight feature to test against?

**Comment by fhoo** [comment]
Just search for flighting in the file. In my current environment I have these lines:
```
    <!-- Flighting Certificate -->
    <add key="DataAccess.FlightingEnvironment" value="" />
    <add key="DataAccess.FlightingCertificateThumbprint" value="" />
    <add key="DataAccess.FlightingServiceCatalogID" value="12719367" />
    <!-- Flighting Cache Folder Name -->
    <add key="DataAccess.FlightingServiceCacheFolder" value="CarbonRuntimeBackup" />
```

And I have another pretty clean environment that looks the same, only the value in the FlightingServiceCatalogID is empty. Also according to the documentation, only that value has to be filled in. I never changed anything else but that CatalogID, unfortunately I can't remember, if I ever had to add that line or just needed to fill the ID.

For testing you can use the flight DisableBuildLoadedRelationsWhenUsingNodeLib and see whether the issue with the join-able tables is fixed, like described in the Yammer [post](https://www.yammer.com/dynamicsaxfeedbackprograms/threads/553067205664768) you liked today ;)

**Comment by Splaxi** [comment]
I just put Test-D365FlightServiceCatalogId together. Then we can make people test it in a controlled fashion, enable or disable.

If they need to add it to the web.config it is still a manual task. My newly deployed PU32 environment already had the FlightingServiceCatalogId element in the web.config file.

It has all been deployed to powershell gallery...

**Pull request merged**
