### PR TITLE
Adding 'add-d365externaluser' function

### PR DESCRIPTION
**Pull request by anderson-joyle**
Add a new user with system user and system administrator. The idea behind this script its to help add partner users into client test/dev environments after a database refresh.

### CODE REVIEW

**Comment by Splaxi** [comment]
Hey!

Thank you for the PR 😀

Don't mind the failed tests for now. I'll play around with your code and see if I find something that needs to be adjusted. 

I'm guessing that the use case is that you're with a customer, and the environment is running under your tenant, and you have to import a user from the partners tenant - right? 

I believe we support that scenario with the present cmdlet for adding users, but might not have documented it... 

With that said, I will still consider merging this in, because it is more explicit in what the user can expect it to do.

Thank you for spending time to share your work 👍

**Comment by anderson-joyle** [comment]
Thanks for your comments.

Yes, function **import-d365aaduser** does the trick. The idea behind my PR is to enable both partner and client tech teams to be able to add a user from external tenants without having to connect into other's Azure AD (since they don't have permission).

My mistake was not checking all your internal functions. There is **New-D365FOUser** and **Add-AadUserSecurity** which do their jobs.

Let me send you a new PR, re-writing my function to make use of internal code (and not reinvent the wheel).

**Comment by Splaxi** [comment]
Let me know if you need a hand or something is unclear.

A small note:
Just write the functions and ignore pester tests and docs (md files). We create does as a part of our release pipeline 😉

**Comment by Splaxi** [comment]
The SkipAzureAd switch on the import-d365aaduser function should give you the structure for how to achieve your goal.

I would love having an explicit function that enables the user to easily understand how to get external users into the system. 

So, please create it, if you feel for it 🤘

**Pull request closed without merging**
