### PR TITLE
Refactor: Remove old and unused cmdlets.

### PR DESCRIPTION
**Pull request by Splaxi**

### CODE REVIEW

**Comment by fhoo** [comment]
That's sad :(
I'm a huge fan of the old label cmdlets.

**Comment by Splaxi** [comment]
Point out which one you want to keep and I'll let them stay. Just trying to remove clutter from the module. 😉

Maybe we should have a better naming for it?

**Comment by fhoo** [comment]
Nice :)
I'm using Get-D365InstalledPackageOld,

**Comment by fhoo** [comment]
Yes, looks promising. Will test on Monday, as I'm not near my Computer over the weekend.

**Comment by Splaxi** [comment]
Awesome.

Take your time and do what you usually do with the cmdlets, to see what works or not - and make sure that naming makes sense 😉

**Comment by fhoo** [comment]
Hi @Splaxi,
my label cmdlets are working like a charm with your cleaned up branch. The only thing I'd change would be the name of the Get-D365PackageLabelResourceFiles cmdlet to be Get-D365PackageLabelResourceFile, i.e. the singular version.
Thanks for taking your time to consider my wishes 🥇😍

**Pull request merged**
