### PR TITLE
Added option to retrieve version of module/package

### PR DESCRIPTION
**Pull request by gertvdh**

### CODE REVIEW

**Comment by Splaxi** [comment]
Great idea Gert!

I created a custom file version function in another module / project. The reason for that was because of this blog post:
https://blogs.technet.microsoft.com/askpfeplat/2014/12/07/how-to-correctly-check-file-versions-with-powershell/

You can see the custom function here:
https://github.com/d365collaborative/ax2012.tools/blob/development/ax2012.tools/internal/functions/get-fileversion.ps1

Could you test things a bit with this new information? I would argue that we simply should display 2 file versions, so we are sure the users are able to compare the versions displayed the file explorer and powershell.

Let me know what you think 🤔

**Comment by gertvdh** [comment]
Hi, I've copied the get-fileversion from the other project as internal function. I'm only getting the fileversions, not the product versions, since that will not be used for 365 assemblies

**Comment by Splaxi** [comment]
Great work Gert!

I'll make sure to uptake the PR later tonight and create a new release.

Thanks for helping out 🤘

**Comment by gertvdh** [comment]
No problem, when released we will be using this one at once in our build pipelines :)

**Pull request merged**
