### PR TITLE
Refactor use az.storage

### PR DESCRIPTION
**Pull request by FH-Inway**
See #361

### CODE REVIEW

**Comment by Splaxi** [comment]
So - I feel like we should take a serious swing at it and make it happen.

Are we on the same page in terms of taking the risk, and fixing whatever people might report?

@FH-Inway  @fhoo ?

**Comment by FH-Inway** [comment]
I'm in :)

**Comment by fhoo** [comment]
Go for it 👍

**Comment by FH-Inway** [comment]
@Splaxi @fhoo New year, let's have another go at this!
I think we can handle the support cases and if push comes to shove, we can always roll back to the previous version and tell people to use `-AllowClobber`.
:rocket:

**Comment by FH-Inway** [comment]
@Splaxi Seems this time, the Azure DevOps Pipeline had an issue. Or did you cancel it manually?

**Comment by Splaxi** [comment]
I'll look into it 😅

**Pull request merged**
