### PR TITLE
About deployable packages

### PR DESCRIPTION
**Pull request by FH-Inway**
@Splaxi 
Was wondering how you feel about adding "conceptual help", i.e. about text files to the module to improve the documentation?

The PR contains a first draft of an about text for deployable packages.

### CODE REVIEW

**Comment by Splaxi** [comment]
The initial thought is: AWESOME 🤘

But looking from a user point of view: 
Why not do it as wiki pages (MD files)? This opens up for linking to cmdlets, making tutorial styled introduction and adding supporting media (gif / video) to help the reader. 

So - where do you see the benefits of pure txt files? Is it from an authoring point of view easier?

**Comment by FH-Inway** [comment]
Full disclosure, I watched several Microsoft videos on PowerShell the last few months and may have had too much of the MS/PS KoolAid :)

The about text files have the advantage that they are automatically integrated in the PS help system.
I agree, .md files would be better, but those are not supported by PS. Hm, maybe we can do something similar to MS, where the about text files are transformed into .md files and put into a references or concepts folder of the wiki? If someone later wants to make them pretty, we could exclude those custom about .md files from the auto transform from text to .md?

**Comment by Splaxi** [comment]
How are the about files mapped into the module? How can I list all available about concepts in the module? 

I'm sure the powershell community has a small tool that can help us 😉

**Comment by Splaxi** [comment]
Personally I'm more than fine with the about files.

But just remember that the more text you write, the more we need to maintain - where the current Comment Based Help is "more" or less automated 😉

**Comment by Splaxi** [comment]
Are you still in favor of getting this as part of the module? If so - I'll merge and release it during the day.

**Comment by FH-Inway** [comment]
Yes, still in favor, thanks.

**Pull request merged**
