### PR TITLE
[Invoke-D365ProcessModules]

### PR DESCRIPTION
**Pull request by ThugPotato**
Created new function Invoke-D365ProcessModules - replaces Invoke-D365ModuleFullCompileSync

- Removed/replace Invoke-D365ModuleFullCompileSync function
- Created new Invoke-D365ProcessModules. Uses Switches/flags to determine what must be executed (better than creating a function per variant of execution)
- Added report deployment possibility to Invoke-D365ProcessModules
- Replace Invoke-D365ModuleFullCompileSync with Invoke-D365ProcessModules in manifest

### CODE REVIEW

**Comment by Splaxi** [comment]
You're a busy man Mr. @ThugPotato 😉

I'll look at it tonight and see if I can make a publish of it. Let me know when you feel it is done, then we can announce it on twitter, so the rest of the world can learn about it. Based on the last few days, it seems that you are learning more about your own use case, and that way the cmdlets / functions evolve. It is fine by me, that we iterate of this a few times and even publish it. But when we first announce it, we should feel confident that the new cmdlets / functions are going to stay in the module for a longer period of time.

Let me know what you think.

**Comment by ThugPotato** [comment]
Thanks!

The functions were created and updated based on incoming ideas and were immediately developed. Looking back I should have spent a bit more time making an overview of the use-case as you stated.

That is what I have done for this PR. In this PR it was my intention to make the function more generic. Using the function with flags to trigger certain flows, instead of creating a function for every flow-variant, seems like the best solution. 
It also seems most extensible for any future development: if a new flow-variant is required it can be added using a new flag and some code.

I'm confident that the new functions are going to stay the same for a long time. There I think it can be announced on the next release :).

**Comment by Splaxi** [comment]
I just did a PR against your branch.

You need to document the remaining 3 parameters:

ExecuteCompile 
ExecuteDeployReports 
ExecuteSync 

https://dev.azure.com/Splaxi/d365fo.tools/_build/results?buildId=1228&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=ce91d5d6-0c55-50f5-8ab9-6695c03ab102&l=299

https://dev.azure.com/Splaxi/d365fo.tools/_build/results?buildId=1228&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=ce91d5d6-0c55-50f5-8ab9-6695c03ab102&l=305

https://dev.azure.com/Splaxi/d365fo.tools/_build/results?buildId=1228&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=ce91d5d6-0c55-50f5-8ab9-6695c03ab102&l=311

**Comment by ThugPotato** [comment]
@Splaxi documentation added for 3 parameters.

**Comment by Splaxi** [comment]
@ThugPotato I made a mistake earlier when creating the first PR against your code, so it got merged into development.

I just created a new PR against your repository. Please merge and push, then we should be good to go.

**Comment by ThugPotato** [comment]
@Splaxi didn't even notice... 
Merged it again now.

**Pull request merged**
