### PR TITLE
Add an option to Invoke-D365ModuleCompile to only generate xRefs

### PR DESCRIPTION
**Pull request by fhoo**
Utilize the new option of the X++ compiler to only generate cross references without actually compiling and modifying the assemblies and PDB files, according to https://community.dynamics.com/365/financeandoperations/b/peter-s-x-developer-blog/posts/spend-less-time-recompiling-microsoft-x-code

### CODE REVIEW

**Comment by torbennehmer** [comment]
Please merge this, it would be a great addition to the module

**Comment by fhoo** [comment]
Hi @Splaxi, what's keeping you from merging this PR? Is there anything missing?

**Comment by Splaxi** [comment]
Merge 0.6.78

**Comment by fhoo** [comment]
> Time - life happened a lot lately 🤯🙄😮

Sorry to hear, I hope you are doing well. And no worries, we are grateful that you took your time to create these awesome tools. 
So thanks for merging but I didn't mean you have to do it immediately, I just was wondered if something was missing 😊

**Comment by torbennehmer** [comment]
I can only agree to that! The tools are second to none!

**Comment by Splaxi** [comment]
> > Time - life happened a lot lately 🤯🙄😮
> 
> Sorry to hear, I hope you are doing well. And no worries, we are grateful that you took your time to create these awesome tools. So thanks for merging but I didn't mean you have to do it immediately, I just was wondered if something was missing 😊

No worries! I'm just grateful that you guys are still invested in the community and **our** module, and I need the nudging from time to time, when life happens. Stay safe 🤘

**Pull request merged**
