### PR TITLE
Fixed case when Id field exceeds character limit

### PR DESCRIPTION
**Pull request by scifimiki**
* Truncated id variable to 20 characters to prevent blocking processing user list from AAD group.

### CODE REVIEW

**Comment by scifimiki** [comment]
The UserInfo table's ID field is limited to 20 characters (nvarchar(20)). When trying to import an AAD group and processing encounters a user with an id which exceeds the limit it blocks the further processing of user list.

**Comment by Splaxi** [comment]
Thanks for the PR 🤘

I'm going to change it to host, instead of verbose. Changing the expected ID of the user needs to be printed. 

You are welcome to add your name and online handle in the notes section, to get credit for the work you have done.

**Comment by Splaxi** [comment]
I believe this is you:

Miklós Molnár (@scifimiki)

Let me know if you want the credit to be public or not. I'll keep it out of the source code until I hear from you.

**Comment by scifimiki** [comment]
@Splaxi: Yes, it can be public, thank you. It's just my first contribution and I did not want to mess up the pull request. :)

**Comment by Splaxi** [comment]
No worries.

I totally remember the feeling from doing pull requests, and still get the same feeling when doing it against repositories where I don't know the maintainer. 

I'm here to help with any questions you might have, but I feel very strongly about giving credits to every single contributor. 

Your name will make it part of the release later today. 

Thanks for taking the time to share your findings with the community 🤘

**Pull request merged**
