### PR TITLE
Added a default value to the AdminSignInName parameter

### PR DESCRIPTION
**Pull request by ibruynin**
Hi there

This works well in the scripts we're using in our team
Not sure if it will for _everyone_ out there

Let me know what your thoughts are.

### CODE REVIEW

**Comment by Splaxi** [comment]
Thank you for sharing 🤘

I'll check it out and maybe ask a few question.

Just ignore the errors for now 😉

**Comment by Splaxi** [comment]
So I'm guessing that you guys are either downloading the VHD files from LCS, and after spinning them up - you add them to your onprem Active Directory - right? Then the UPN of the current user correspond to an valid e-mail address, which is either synced to your Azure Active Directory or is simply a stand alone user in the Azure Active Directory - right?

**Comment by ibruynin** [comment]
Yes - that’s right!
The vhd is in the domain and we use our own user as admin on the dev box 

Best regards,
Ian

**Comment by Splaxi** [comment]
We will not uptake this PR, as this is an edge use case we don't feel will be used broadly. 

We hope that you will pitch other things and ideas anyways.

**Pull request closed without merging**
