### PR TITLE
Fix: Try to clean up all http client objects. Could explain sessions …

### PR DESCRIPTION
**Pull request by Splaxi**
…that end up dead.

### CODE REVIEW

**Comment by FH-Inway** [comment]
Hey @Splaxi , I noticed commit [a4dfa90](https://github.com/d365collaborative/d365fo.tools/pull/537/commits/a4dfa9056ab017eece269b8886de86380d0c0fee) added a `RetryTimeout `parameter to the `Invoke-D365LcsEnvironmentStart` command.
A pipeline of mine is using that command to start a CHE T1 environment. Yesterday, it worked. Today, I'm hitting 429 status codes. However, the environment is shown as started in LCS and I can log into it. I also noticed that the messages about the 429 code contain an "Attempt (0)" at the end. Shouldn't that increase?

Currently, I have 6 messages in my pipeline execution.

`[07:32:32][Invoke-RequestHandler] Hit a 429 status code. Will wait for: 267 seconds before trying again. Attempt (0)`

I'm guessing that adding the parameter will resolve the issue. However, I'm wondering if that parameter shouldn't get a default value other than 0?

**Comment by FH-Inway** [comment]
After an additional 5 messages, I finally got the expected `IsSuccess=False` message (the pipeline tries the command until it returns this result). I guess a bit later, the 60 minute limit for a pipeline hosted on a Microsoft agent would have canceled the run anyway.

**Comment by Splaxi** [comment]
I would love to see the entire log, if possible?

It has been pretty hard to test these things, as I implemented them before they were available for the LCS API. I did some preliminary testing against D365HR, which have had 429 for a longer period.

I'm 98% sure that I got it to count as intended, but would love to learn if I missed something obvious in my implementation.

**Comment by FH-Inway** [comment]
I sent you an email with the log.

**Comment by FH-Inway** [comment]
Hey @Splaxi , did you have a chance to take a look at the logs I sent you? I'm currently experiencing this again and was wondering if there is a better way to check if the machine is running instead of resending the start command, which seems to result in the 429 code after the first time.

**Comment by Splaxi** [comment]
Rumor has it that we might a new endpoint, that will offer better insight to the status of a given environment 🤞

**Comment by FH-Inway** [comment]
Hey @Splaxi , thanks for adding the new endpoints to the tools so fast. I got a chance today to include the new `Get-D365LcsEnvironmentMetadata` in my pipelines to start and stop CHEs. So now instead of repeating the start/stop commands till they fail, I check the `DeploymentStatusDisplay` of the environment's metadata. Seems to work well so far.

**Comment by Splaxi** [comment]
Awesome news @FH-Inway 

Would love to see a blog post / LinkedIn article or even a wiki page here on github about your findings 😉🤞

**Pull request merged**
