### PR TITLE
Add function for windows defender rules (performance)

### PR DESCRIPTION
**Pull request by DarkSmile92**
With the installation of Visual Studio 2019 I also found out about windows defender rules that can improve the performance while working on a DevBox.

I added a function to add those rules to the windows defender - if it's enabled.
About the tags in the synopsis: I was unsure what to write there, please check it and add accordingly.

Hopefully this function is useful for the d365fo.tools module.

### CODE REVIEW

**Comment by Splaxi** [comment]
Hi @DarkSmile92 

That is just awesome what you did with the defender stuff.

Did you already test that these excludes made a difference? On what environment did you test it? Did you run it on a Tier1 deployed from LCS onto an Azure subscription? What about a Tier1 Microsoft hosted (via the license)? Or did you try it on a onebox (downloaded VHD)?

I can see that you placed the `Get-WindowsDefenderStatus` inside the same file as the new public cmdlet / function. I'm going to move that into a separate file, in our internal sub folder, where all non-public cmdlets / funtions live their live.

Let me more about your testing, while I make it part of our release.

**Comment by DarkSmile92** [comment]
Hey @Splaxi , good idea to move the function to a separate file, I was unsure about the structure.

I tested these changes on multiple environments listed below.
The greatest impact was noticed on onebox on-prem maschines (DevBoxes in our case).

## Onebox VHD (on-prem)
Performance measured as proof:
- DB Sync: `-3 min`
- Deployable Package creation: <span style="color: green;">`-2 min`</span>
- Full build of all standard models: `-7 min`
- Metadata search (cold start, no cache): `-30 sec` (measure the time with a search, add rules, reboot maschine, open VS, run search again)
- Loading the debugger with breakpoint in `SalesFormLetter.run` and posting a sales invoice: `-6 sec`

## Tier 1 on Azure (deployed via LCS - customer license)
Performance measured as proof:
- DB Sync: `-2 min`
- Full build of all standard models: `-5 min`

Those are the tests I measured the time with, other things "felt" faster, but I did only measure times with those.
Sorry I didn't make more test cases to verify ☹️

**Comment by Splaxi** [comment]
Is `-2 min` equal to 2 minutes faster? 🤔

I just wanted to make sure what you tested, so I could plan any testing myself and what to expect.

Thanks for sharing the overview!

**Comment by DarkSmile92** [comment]
I knew my description could be misleading and was unsure if I should wirte "+" or "-" for the times 😁 `-2 min` means 2 minutes faster than before.

**Comment by Splaxi** [comment]
I'm very impressed with you digging skills.

I'll make it part of our release and share it with the community tonight!

**Comment by DarkSmile92** [comment]
Thanks a lot!
To give more details about the OneBox:
<details><summary>Show system specs</summary>

`PS C:\windows\system32> Get-ComputerInfo`
```ps
WindowsBuildLabEx                                       : 14393.3630.amd64fre.rs1_release.200407-1730
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : ServerDatacenterEval
WindowsInstallationType                                 : Server
WindowsInstallDateFromRegistry                          : 14.07.2017 23:17:15
WindowsProductId                                        : 00377-10000-00000-AA360
WindowsProductName                                      : Windows Server 2016 Datacenter Evaluation
WindowsRegisteredOrganization                           : MS
WindowsRegisteredOwner                                  : DCS
WindowsSystemRoot                                       : C:\windows
BiosCharacteristics                                     : {4, 7, 9, 11...}
BiosBIOSVersion                                         : {VRTUAL - 4001628, BIOS Date: 04/28/16 13:00:17  Ver: 
                                                          09.00.06, BIOS Date: 04/28/16 13:00:17  Ver: 09.00.06}
BiosBuildNumber                                         : 
BiosCaption                                             : BIOS Date: 04/28/16 13:00:17  Ver: 09.00.06
BiosCodeSet                                             : 
BiosCurrentLanguage                                     : enUS
BiosDescription                                         : BIOS Date: 04/28/16 13:00:17  Ver: 09.00.06
BiosEmbeddedControllerMajorVersion                      : 
BiosEmbeddedControllerMinorVersion                      : 
BiosFirmwareType                                        : Bios
BiosIdentificationCode                                  : 
BiosInstallableLanguages                                : 1
BiosInstallDate                                         : 
BiosLanguageEdition                                     : 
BiosListOfLanguages                                     : {enUS}
BiosManufacturer                                        : American Megatrends Inc.
BiosName                                                : BIOS Date: 04/28/16 13:00:17  Ver: 09.00.06
BiosOtherTargetOS                                       : 
BiosPrimaryBIOS                                         : True
BiosReleaseDate                                         : 28.04.2016 02:00:00
BiosSeralNumber                                         : 7406-5345-7838-2037-6289-8314-84
BiosSMBIOSBIOSVersion                                   : 090006 
BiosSMBIOSMajorVersion                                  : 2
BiosSMBIOSMinorVersion                                  : 3
BiosSMBIOSPresent                                       : True
BiosSoftwareElementState                                : Running
BiosStatus                                              : OK
BiosSystemBiosMajorVersion                              : 
BiosSystemBiosMinorVersion                              : 
BiosTargetOperatingSystem                               : 0
BiosVersion                                             : VRTUAL - 4001628
CsAdminPasswordStatus                                   : Unknown
CsAutomaticManagedPagefile                              : True
CsAutomaticResetBootOption                              : True
CsAutomaticResetCapability                              : True
CsBootOptionOnLimit                                     : 0
CsBootOptionOnWatchDog                                  : 0
CsBootROMSupported                                      : True
CsBootStatus                                            : {0, 0, 0, 0...}
CsBootupState                                           : Normal boot
CsCaption                                               : ACDC01VMS770
CsChassisBootupState                                    : Safe
CsChassisSKUNumber                                      : 
CsCurrentTimeZone                                       : 120
CsDaylightInEffect                                      : True
CsDescription                                           : AT/AT COMPATIBLE
CsDNSHostName                                           : ACDC01VMS770
CsDomain                                                : ALPLA-DMZ
CsDomainRole                                            : StandaloneServer
CsEnableDaylightSavingsTime                             : True
CsFrontPanelResetStatus                                 : Unknown
CsHypervisorPresent                                     : True
CsInfraredSupported                                     : False
CsInitialLoadInfo                                       : 
CsInstallDate                                           : 
CsKeyboardPasswordStatus                                : Unknown
CsLastLoadInfo                                          : 
CsManufacturer                                          : Microsoft Corporation
CsModel                                                 : Virtual Machine
CsName                                                  : ACDC01VMS770
CsNetworkAdapters                                       : {Ethernet 15}
CsNetworkServerModeEnabled                              : True
CsNumberOfLogicalProcessors                             : 8
CsNumberOfProcessors                                    : 1
CsProcessors                                            : {Intel(R) Xeon(R) CPU           X5675  @ 3.07GHz}
CsOEMStringArray                                        : {[MS_VM_CERT/SHA1/9b80ca0d5dd061ec9da4e494f4c3fd1196270c22], 
                                                          00000000000000000000000000000000, To be filed by MSFT}
CsPartOfDomain                                          : False
CsPauseAfterReset                                       : 3932100000
CsPCSystemType                                          : Desktop
CsPCSystemTypeEx                                        : Desktop
CsPowerManagementCapabilities                           : 
CsPowerManagementSupported                              : 
CsPowerOnPasswordStatus                                 : Unknown
CsPowerState                                            : Unknown
CsPowerSupplyState                                      : Safe
CsPrimaryOwnerContact                                   : 
CsPrimaryOwnerName                                      : DCS
CsResetCapability                                       : Other
CsResetCount                                            : -1
CsResetLimit                                            : -1
CsRoles                                                 : {LM_Workstation, LM_Server, SQLServer, NT...}
CsStatus                                                : OK
CsSupportContactDescription                             : 
CsSystemFamily                                          : 
CsSystemSKUNumber                                       : 
CsSystemType                                            : x64-based PC
CsThermalState                                          : Other
CsTotalPhysicalMemory                                   : 33553960960
CsPhyicallyInstalledMemory                              : 32768000
CsUserName                                              : 
CsWakeUpType                                            : PowerSwitch
CsWorkgroup                                             : ALPLA-DMZ
OsName                                                  : Microsoft Windows Server 2016 Datacenter Evaluation
OsType                                                  : WINNT
OsOperatingSystemSKU                                    : 80
OsVersion                                               : 10.0.14393
OsCSDVersion                                            : 
OsBuildNumber                                           : 14393
OsHotFixes                                              : {KB4534126, KB3186568, KB3192137, KB4023834...}
OsBootDevice                                            : \Device\HarddiskVolume1
OsSystemDevice                                          : \Device\HarddiskVolume1
OsSystemDirectory                                       : C:\windows\system32
OsSystemDrive                                           : C:
OsWindowsDirectory                                      : C:\windows
OsCountryCode                                           : 43
OsCurrentTimeZone                                       : 120
OsLocaleID                                              : 0c07
OsLocale                                                : de-AT
OsLocalDateTime                                         : 12.05.2020 11:42:23
OsLastBootUpTime                                        : 16.04.2020 15:39:25
OsUptime                                                : 25.20:02:57.5485961
OsBuildType                                             : Multiprocessor Free
OsCodeSet                                               : 1252
OsDataExecutionPreventionAvailable                      : True
OsDataExecutionPrevention32BitApplications              : True
OsDataExecutionPreventionDrivers                        : True
OsDataExecutionPreventionSupportPolicy                  : OptOut
OsDebug                                                 : False
OsDistributed                                           : False
OsEncryptionLevel                                       : 256
OsForegroundApplicationBoost                            : Maximum
OsTotalVisibleMemorySize                                : 32767540
OsFreePhysicalMemory                                    : 9000036
OsTotalVirtualMemorySize                                : 37486132
OsFreeVirtualMemory                                     : 13997640
OsInUseVirtualMemory                                    : 23488492
OsTotalSwapSpaceSize                                    : 
OsSizeStoredInPagingFiles                               : 4718592
OsFreeSpaceInPagingFiles                                : 4414636
OsPagingFiles                                           : {C:\pagefile.sys}
OsHardwareAbstractionLayer                              : 10.0.14393.3297
OsInstallDate                                           : 15.07.2017 01:17:15
OsManufacturer                                          : Microsoft Corporation
OsMaxNumberOfProcesses                                  : 4294967295
OsMaxProcessMemorySize                                  : 137438953344
OsMuiLanguages                                          : {en-US}
OsNumberOfLicensedUsers                                 : 0
OsNumberOfProcesses                                     : 100
OsNumberOfUsers                                         : 3
OsOrganization                                          : MS
OsArchitecture                                          : 64-bit
OsLanguage                                              : en-US
OsProductSuites                                         : {TerminalServices, DatacenterEdition, 
                                                          TerminalServicesSingleSession}
OsOtherTypeDescription                                  : 
OsPAEEnabled                                            : 
OsPortableOperatingSystem                               : False
OsPrimary                                               : True
OsProductType                                           : Server
OsRegisteredUser                                        : DCS
OsSerialNumber                                          : 00377-10000-00000-AA360
OsServicePackMajorVersion                               : 0
OsServicePackMinorVersion                               : 0
OsStatus                                                : OK
OsSuites                                                : {TerminalServices, DatacenterEdition, 
                                                          TerminalServicesSingleSession}
OsServerLevel                                           : FullServer
KeyboardLayout                                          : en-US
TimeZone                                                : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
LogonServer                                             : \\ACDC01VMS770
PowerPlatformRole                                       : Desktop
HyperVisorPresent                                       : True
HyperVRequirementDataExecutionPreventionAvailable       : 
HyperVRequirementSecondLevelAddressTranslation          : 
HyperVRequirementVirtualizationFirmwareEnabled          : 
HyperVRequirementVMMonitorModeExtensions                : 
DeviceGuardSmartStatus                                  : Off
DeviceGuardRequiredSecurityProperties                   : 
DeviceGuardAvailableSecurityProperties                  : 
DeviceGuardSecurityServicesConfigured                   : 
DeviceGuardSecurityServicesRunning                      : 
DeviceGuardCodeIntegrityPolicyEnforcementStatus         : 
DeviceGuardUserModeCodeIntegrityPolicyEnforcementStatus : 
```

</details>

**Pull request merged**
