### PR TITLE
[Invoke-D365ModuleFullCompileSync] New command: compile and sync by module (match)

### PR DESCRIPTION
**Pull request by ThugPotato**
New command made to compile and sync module(s). 

Compile and sync is done using the Invoke-D365ModuleFullCompile and Invoke-D365DBSyncPartial functions.

### CODE REVIEW

**Comment by ThugPotato** [comment]
> For the record, you don't need to provide the pester test for the parameters and you don't need to create the docs file.

Oh great. Didn't know that.

Thanks!

**Comment by Splaxi** [comment]
We actually only care about the code.

The tests will be based on the code and ensure that we don't have drifting changes or break backwards compatibility (unintentionally). 

The docs are based on the function itself, so the online documentation is 100% identical to the one in module on your machine.

**Comment by ThugPotato** [comment]
Got it!

Do you perhaps have any documentation on debugging these module functions? 

When working on this new function my only way of debugging was adding 'Write' statements... Sadly this was the best way of debugging I found.

**Comment by ThugPotato** [comment]
@Splaxi I have noticed that for model compile and sync with 10+ models the advantage of using the function over doing it in Visual Studio is gone.

I figured out some rework where the advantage remains. I will try and validate it, check the code and commit my changes on the same branch.

Can you hold on with the merge until I have pushed these 'fixes'? Thx!

**Comment by Splaxi** [comment]
I'm waiting for you to test your code and get back

**Comment by ThugPotato** [comment]
@Splaxi reworked code was checked in. 

PS: Pester test was changed before your comment about not having to change these tests.

**Comment by Splaxi** [comment]
I fixed one tiny little thing.

We try to keep internal functions **without** the D365. This simplifies our troubleshooting, when jumping between different functions.

So your Get-D365SyncElements is now Get-SyncElements

**Pull request merged**
