### PR TITLE
[Import-D365SqlBackup] New function import SQL backup

### PR DESCRIPTION
**Pull request by ThugPotato**
- Added function Import-D365SqlBackup for importing SQL backup file into environment database
- Added function to manifest
- Added module variable for default SQL Binary tools folder

### CODE REVIEW

**Comment by Splaxi** [comment]
Thank you for the PR.

You're hitting a delicate spot with this. 

On one side I know that different projects around the world is depending heavily on bak files between Tier1 environments, while others are sticking to bacpac files.

I'm a huge fan of dbatools, a powershell module that I actually used to help work on in the early days. Dbatools is solving the backup / restore story so brilliantly and is driven by a community that is nothing less than magnificent.

I know first hand how hard it is to make everything work when working with backup / restore, when the different environments might be configured differently. 

I want the best tool for the different job and knowing that dbatools exists and they are light-years ahead of the game, I'm having a hard time supporting restore in D365FO.tools... 

Let me know your thoughts and we can have a discussion about what makes sense.

**Comment by ThugPotato** [comment]
Thx for the feedback @Splaxi. I was unaware that the entire module of DBATools already exists. Should have done a bit more research for creating this :p.

These backup/restore tools support way more different configurations than the one in Import-D365SqlBackup making it a bit (by lack of phrasing) 'useless'.

Reason for creating this tool was to reduce time spent on restoring a database specifically in a D365FO T1 environment (no more Wizards in SQL management).

However, correct me if I'm wrong but if DBATools would be used for database restore, the user would have to pass a lot of parameters (database server, database names, credentials,...) that can already be provided by the D365FO.Tools. 

I think there's an opportunity to reduce time spent by using D365FO.Tools combined with dbatools. This might be possible by 
• Simply exposing the default module/global variables of the D365FO.Tools so that the user may use these variables for any other tool/function.  
• Create wrapper functions around the DBATools and use it specifically for the D365FO functionality.

Let me know what you think about it, and thanks again for the feedback!

**Comment by Splaxi** [comment]
Import-Module dbatools 
Backup-DbaDatabase -SqlInstance . -BackupDirectory c:\temp -Type Full -CreateFolder -CompressBackup -Database AXDB

Import-Module dbatools 
Restore-DbaDatabase -SqlInstance . -Path "c:\temp\d365fo.tools\FinancialsTest_AXDB_20181129.bak" -DatabaseName AXDB -ReplaceDbNameInFile -WithReplace
Rename-DbaDatabase -SqlInstance . -Database AXDB -LogicalName "<DBN>_<FT>"

The above commands are working out of the box for any Tier1 environments, with the little note that on cloud hosted you need to run the Set-D365SysAdmin once after deployment. 

https://github.com/d365collaborative/d365fo.tools/blob/development/docs/Set-D365SysAdmin.md

We could create a wiki how to, that shows how to do backup and restore in detail, for each type

**Comment by Splaxi** [comment]
@fhoo I can see that you actually are reading along.

What is your take on all of this?

**Comment by fhoo** [comment]
I liked your comment to save me the typing ;)
From my point of view, it makes no sense to reinvent the wheel. DBATools is just an Install-Module away and passing the parameters can be reduced to a minimum, like shown in your examples. Also one can get environment info by using the D365FO.Tools if needed. Hence I like the idea of „just“ putting a good how to into the wiki which everyone can use in one's own scripts. 
To even more simplify the task for the average D365FO user, I‘d also can imagine specialized cmdlets doing the backup/restore using the DBATools, reducing the needed parameters to specify to a minimum, but benefit from the experience of the DBATools community.

**Comment by Splaxi** [comment]
I'm not super excited about creating a wrapper around the dbatools cmdlets, because it requires us to support what ever they might have to change in their end.

Wiki is what I would recommend, and maybe write a guide on how to use the output from our tools to create a hash table to utilize splatting in combination with dbatools.

**Comment by fhoo** [comment]
That’s a good point. I agree 👍

**Comment by ThugPotato** [comment]
@Splaxi making a Wiki does make more sense indeed! :)

**Comment by Splaxi** [comment]
Then we are going to close this one.

If any one of you want to help out with the wiki part, please let me know. Otherwise this will be planned over the next few weeks.

**Pull request closed without merging**
